# Generated by Django 2.2.3 on 2019-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('aadharnumber', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('statename', models.CharField(max_length=20)),
                ('countryname', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('mobilenumber', models.CharField(max_length=13)),
            ],
        ),
    ]
