# Generated by Django 2.2.3 on 2019-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_userfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=20)),
                ('roomchoice', models.CharField(choices=[('single', 'single'), ('double', 'double')], max_length=10)),
                ('extracharge', models.IntegerField()),
                ('servicecharge', models.IntegerField()),
                ('numberofroom', models.IntegerField()),
            ],
        ),
    ]
