# Generated by Django 2.2.3 on 2019-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rooms_roomcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomcharge',
            field=models.IntegerField(default=0),
        ),
    ]
