# Generated by Django 2.2.3 on 2019-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20190902_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='numberofroom',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
