# Generated by Django 2.2.3 on 2019-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20190904_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='menucard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtitle', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Salad', 'Salad'), ('Snacks', 'Snacks'), ('South Indian Dishes', 'South Indian Dishes'), ('Dal ', 'Dal '), ('Soup', 'Soup'), ('Vegetables ', 'Vegetables'), ('Raita', 'Raita'), ('Rice', 'Rice '), ('Roti', 'Roti'), ('Cold Beverages ', 'Cold Beverages '), ('Chinese Dishes', 'Chinese Dishes'), ('Hot Beverages', 'Hot Beverages '), ('Thali Meals ', 'Thali Meals '), ('Desserts ', 'Desserts')], max_length=100)),
                ('foodname', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
