# Generated by Django 2.2.3 on 2019-10-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_menucard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='numberofroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=10),
        ),
    ]
