# Generated by Django 2.2.3 on 2019-10-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20191016_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='perroomperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.IntegerField(default=1)),
                ('personname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=13)),
                ('aadhar', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='numberofroom',
        ),
        migrations.AddField(
            model_name='rooms',
            name='totalroom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
