# Generated by Django 2.2.3 on 2019-11-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20191018_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('MARKETING AND ADVERTISING', 'MARKETING AND ADVERTISING'), ('ACCOUNTING', 'ACCOUNTING'), ('PURCHASING', 'PURCHASING'), ('EVENT PLANNER', 'EVENT PLANNER'), ('ASSISTANT HOTEL MANAGER', 'ASSISTANT HOTEL MANAGER'), ('HOTEL MANAGER', 'HOTEL MANAGER')], max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('fathername', models.CharField(max_length=30)),
                ('aadharnumber', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='guestservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('SUPERVISOR OF GUEST SERVICES', 'SUPERVISOR OF GUEST SERVICES'), ('FRONT DESK SUPERVISOR', 'FRONT DESK SUPERVISOR'), ('KITCHEN MANAGER', 'KITCHEN MANAGER'), ('RESTURANT MANAGER', 'RESTURANT MANAGER')], max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('fathername', models.CharField(max_length=30)),
                ('aadharnumber', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='supportstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('FRONT DESK CLERK', 'FRONT DESK CLERK'), ('PORTERS', 'PORTERS'), ('CONCIERGES', 'CONCIERGES'), ('HOUSEKEEPING', 'HOUSEKEEPING'), ('ROOM SERVICE', 'ROOM SERVICE'), ('WAITER/WAITRESS', 'WAITER/WAITRESS'), ('KITCHEN STAFF', 'KITCHEN STAFF')], max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('fathername', models.CharField(max_length=30)),
                ('aadharnumber', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=13)),
            ],
        ),
    ]
