# Generated by Django 2.2.3 on 2019-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_administrative_guestservices_supportstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrative',
            name='dateofjoining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='administrative',
            name='marritalstatus',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestservices',
            name='dateofjoining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guestservices',
            name='marritalstatus',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='dateofjoining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='marritalstatus',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrative',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='guestservices',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6),
        ),
    ]
