# Generated by Django 2.2.3 on 2019-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20191108_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perroomperson',
            name='bookingid',
        ),
        migrations.AddField(
            model_name='perroomperson',
            name='Pbookid',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
