# Generated by Django 2.2.3 on 2019-11-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20191118_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroomperson',
            name='sl',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
